version: '3.4'

services:
  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    networks:
    - proxybackend
    ports:
    - "9000:9080"
    - "9001:9081"
 
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    networks:
    - proxybackend
    ports:
    - "7080:7080"
    - "7081:7081"
 
 
  productsapi:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: ProductsApi/Dockerfile
    networks:
    - proxybackend
    ports:
    - "8080:8080"
    - "8081:8081"
      



networks:
  proxybackend:
    name: proxybackend
    driver: bridge
